### ISSUE TITLE
Frame not being filled

### ISSUE THREAD

**Issue by Lazyfattree** [adafruit/pi_video_looper#10]
Is there another way of forcing my screen to give the full video, because at the moment I got full black borders. Tried all overscan possibilities. force hdmi. gave the correct mode and group for what edid gave me as anwser but nothing. 

Image is still to small to fill the screen

**Comment by tdicola** [comment]
Check the omxplayer command line parameters to see if perhaps there is a value to zoom in or crop the video: https://github.com/popcornmix/omxplayer  I don't see anything off hand, but if you do find something you can pass it to omxplayer in the video looper by editing the /boot/video_looper.ini file on this line: https://github.com/adafruit/pi_video_looper/blob/master/video_looper.ini#L93
