### ISSUE TITLE
Git requirement on installer not needed.

### ISSUE THREAD

**Issue by yeyeto2788** [adafruit/pi_video_looper#105]
Base on the installation guide https://learn.adafruit.com/raspberry-pi-video-looper/installation#install-commands-2277650-11 in order to clone this repository we need git to be installed already so I guess that https://github.com/adafruit/pi_video_looper/blob/master/install.sh#L21 could be changed to 
```bash
apt -y install uild-essential python3-dev
```

**Comment by tofuSCHNITZEL** [comment]
yes but it could also be someone copied the zip file of the repo or got the files via SCP to the pi. and for the install of hello_video we need git so this is there to make sure it will be available regardless of how the people got the installer on their pi.
