### ISSUE TITLE
file permission issue

### ISSUE THREAD

**Issue by andyzeo** [adafruit/pi_video_looper#106]
I've noticed that while in copy mode the video is copied when I place the USB stick, but once I remove and reboot the pi, the video at the folder doesn't play, I tried using CHMOD 755 on the file and it didn't work, I tried 777 and now it plays, I don't want to keep using this level of permission for execution though, but it was the only solution I have found. nonetheless, once the script overwrites the file, the execution permission problem comes back again, since the script saves the new video with the default permissions that don't allow for execution.
It's just annoying to have to fix the file manually in this latest version. I've done a clean pi install and then installed the file, no premade img.
I hope I'm not mistaken about something, but it would be great if the script worked as intended by you guys

cheers and all my best

**Comment by tofuSCHNITZEL** [comment]
Sorry, cant reproduce the issue... since the video looper process should run as root there should be no issue reading the file after the copymode created it... just tested this with a fresh install and did not face any of your described issues.
