### ISSUE TITLE
Gratitude

### ISSUE THREAD

**Issue by retromodcoza** [adafruit/pi_video_looper#107]
I'm extremely thankful to the author for this script and setup. 

I was looking for a way to easily loop a video explaining how to use my bitcoin ATM , and I had a raspberry pi lying around for a base.

The end result works perfectly : 
https://ibb.co/sVZJSb0

The world is a better place with people like you.

**Comment by tofuSCHNITZEL** [comment]
Great! Thanks for the feedback.
