### ISSUE TITLE
Vnc and Anydesk Problem (scritp doesn´t let use them)

### ISSUE THREAD

**Issue by GeoIH** [adafruit/pi_video_looper#111]
Hi everyone, i've install the pi_video_looper (works fine), but there's a trouble when I try to logging to the graphical desktop via "VNC" (local network)  or "Anydesk" (internet).  and the problem is don't allow view or manage the raspberry by graphical desktop. Maybe there's a way to start the video_looper after the graphic enviorament? 

Thank you in advance for your help.

**Comment by tofuSCHNITZEL** [comment]
Currently the video_looper is designed to only work on Raspbian Lite without desktop environment
