### ISSUE TITLE
Command terminal visible on RPi4

### ISSUE THREAD

**Issue by Alladinsane** [adafruit/pi_video_looper#118]
***EDIT EDIT:  I tried other tacts to get the desktop up before the looper started and rewrote my installation to be managed by systemd instead of supervisor. That worked well, except that now there is an error about the drive being already mounted that pops up and blocks the screen whenever a USB is inserted. It still works and the error is hidden behind the video, but blocks the countdown timer.

**EDIT: Following my gut that the issue is somehow caused by supervisor starting up the looper with a terminal instead of a desktop, I implemented a *pretty hacky* work-a-round. I edited the supervisor control script to force it to load the desktop before starting up video_looper. At first, this seemed to work, but when I attempted to go to the desktop, I got stuck in a loop where it kept asking for the login. Once I set autorestart to false, this was fixed. 

  video_looper.conf
  ```
  [program:desktop]
  command=startx
  autostart=true
autorestart=false
  
  [program:video_looper]
  ...
  ```
You don't see the desktop before video looper takes over, but now everything works as expected. There's no command prompt on my screen, and I can even use the ESC to close out of videolooper and get to the desktop. There is still an error message that pops up when hotswapping usb drives, but it's hidden beneath the looper and the video, and so never visible the end user.

In my case, I wanted my box as idiot proof as possible, so once I had the terminal hidden and the login loop solved, I used the existing config to disable keyboard control, and got something resembling the behavior I was after, if I took a hacky road to get there.

I'm probably missing something really simple, like some config to make supervisor wait for a desktop before launching programs, et al. I'm hoping this trail of bread crumbs helps someone else get to a better solution.
**END EDIT

My RPi4 Model B is an OOB install of the most recent raspbian using RPi Imager. I installed pi_video_looper following the guide, and it works pretty well, giving me 4k output, which was a requirement... however....

There is some weirdness around how it is running on RPi4. This may be related to the issue others are reporting with the "Esc" key not working. What I am finding is that, although videolooper is starting on boot and displaying the "Insert USB" screen, the shell cursor is still visible over top of it. 

Pressing Esc on a connected keyboard does nothing, however, it is a fully functional terminal prompt. If I type a simple command like "ls", I get the directory listing for the Pi users home directory. In addition, once a command is executed, even just pressing enter, the full command prompt(pi@raspberrypi:~$) becomes and remains visible. 

None of this is visible when a video is playing. However, as a foolproof Plug and Play solution I can turn over to a co-worker, I wish the command prompt wasn't exposed.

OOC, I tried installing it on the current version of raspbian lite(command prompt only), and couldn't get that working at all. I then tried going to back to the next most recent version of Raspbian, from Feb 2020,  and installing on that, but I got the same result as I do with the most recent raspbian.

Curiously, and perhaps a clue: On first launch, the very first time video_looper is started up from a fresh install using the install script, it works perfectly. The cursor is not there. The ESC key takes you back to the Desktop. Executing the reload.sh script from a terminal launches it again, and it works. Something goes awry once it starts on boot, because after the Pi is rebooted, video_looper comes back up with this issue, and it never goes away again. 

From the "Insert USB" screen and its available command prompt. I've tried stopping videolooper, bringing up a desktop with startx(this works) and then reloading videolooper using a new terminal window, and that gets me a black screen from which I cannot escape. If I wait long enough, a mouse pointer appears, and I can move it about. But I cannot get out of this window nor does inserting a usb drive do anything. If I reboot  again, I'm back to my "Insert USB" command prompt screen, and just type startx to get a desktop, the desktop loads but video_looper is now hidden behind it. I can still insert a USB and have the videos played, but "Insert USB" screen is lost to me forever.  I can pop open a terminal, kill videolooper using Supervisor, and attempt to restart it from that same terminal, but this again launches to same black screen as previously mentioned.

**Comment by tofuSCHNITZEL** [comment]
sorry for the late reply... generally Its not recommended to run the video_looper on something else than the LITE version of rasperryos.
would you like to share your systemd conversion? I would like to migrate away from supervisor though I also discovered issues with systemd namely if its not running as root there are issues with the mounting
