### ISSUE TITLE
video looper and crontab

### ISSUE THREAD

**Issue by JoseVidal17** [adafruit/pi_video_looper#119]
When I use the video looper I have a python script that runs a volume controller, this script is configured in the crontab to be searched every minute and in case of not being run it, but whenever I start the crontab does not run the script if I do not have to close the videolooper, and I am interested that it is running during the video looper. What can I do?

**Comment by JonnyTech** [comment]
Please post a copy of your script plus details on the operating system that you are running.

**Comment by tofuSCHNITZEL** [comment]
will close because of inactivity.
