### ISSUE TITLE
NTFS usb possible

### ISSUE THREAD

**Issue by quintendewilde** [adafruit/pi_video_looper#12]
I have files that are over 4gb in size is it possible to let the raspberry read ntfs format usb's?

**Comment by tofuSCHNITZEL** [comment]
check out v1.2.6 of my fork for ntfs support
https://github.com/tofuSCHNITZEL/pi_video_looper

**Comment by ladyada** [comment]
@tofuSCHNITZEL Tobias, it's unlikely we'll get to do more maintenance on this code, would you like to take over updating it and add your changes? we'd be grateful and so would a large number of Pi users :)

**Comment by tofuSCHNITZEL** [comment]
sure! could you contact me via email so we can work out the details? office@bitconnect.at

**Comment by tofuSCHNITZEL** [comment]
@quintendewilde its possible since v1.0.2 in this repository.
