### ISSUE TITLE
Safely Power down the PI from the looper application

### ISSUE THREAD

**Issue by timsterathome** [adafruit/pi_video_looper#120]
I'm not a Python expert but write apps professionally for Linux using C/C++.
Would it be possible to power down the PI from the looper application by adding something like this to  _handle_keyboard_shortcuts():

                if event.key == pygame.K_p:
                    self._print("p was pressed, shutting down...")
                    self._player.stop(3)
                    subprocess.run(['sudo', 'shutdown', 'now'])

**Comment by tofuSCHNITZEL** [comment]
Hi,
check out version 1.0.8. it includes "p" keyboard shortcut for shutdown.
cheers!
