### ISSUE TITLE
rpi4 output same video on both micro hdmi at the same time

### ISSUE THREAD

**Issue by BelgarionNL** [adafruit/pi_video_looper#123]
hi is this possible?

**Comment by pi43r** [comment]
I'm wondering the same. Did you try it out?

**Comment by jnsprnw** [comment]
This seems to be a different use case than #100. Here, the question would be to have the same output on both HDMI, while the other issue is about two different outputs.
But I guess that both options are not working. Is that correct, @tofuSCHNITZEL?
