### ISSUE TITLE
Add Links In README

### ISSUE THREAD

**Issue by MohanMaker** [adafruit/pi_video_looper#131]
Love this project! 

I think two links should be added to the readme.  
1. The [videolooper.de](https://videolooper.de) website has awesome pre-compiled versions of the Raspberry Pi operating system. 
2. It seems that Raspberry Pi released a ["legacy" version of Raspberry Pi OS ](https://www.raspberrypi.com/news/new-old-functionality-with-raspberry-pi-os-legacy/) which still supports OMX player but is otherwise up to date. Instead of saying that this project only works with versions of Raspberry Pi OS up to 5/7/21, you could indicate that people should use the legacy version of the OS.

**Comment by tofuSCHNITZEL** [comment]
Thanks for the feedback.
I have added the info to the README. (didn't know the legacy os existed. good find, thanks!)
