### ISSUE TITLE
add support for CEC-client to control HDMI hardware

### ISSUE THREAD

**Issue by christiansievers** [adafruit/pi_video_looper#138]
would it make sense to add support for CEC? This would enable a Raspberry to control HDMI hardware, not just turning it on and off but also control the volume, etc. For more info see e.g. here https://pimylifeup.com/raspberrypi-hdmi-cec/

p.s. I'm aware of the dangers of adding too many features. The beauty of this project is how simple it is, which makes it so reliable, and it should definitely stay that way. However, this does sound like a seriously useful thing to add. I'm curious what you think @tofuSCHNITZEL 

edited because I sent this off too fast

**Comment by SamVimes78** [comment]
What do you need cec support for? I simply installed cec-utils and created a cronjob that turns on/off the attached monitor during night (and starts/stops video looper). We have 4 loopers running in our shop and they turn on/off automatically only during opening times.

I wonder why you'd need video looper to control the volume!?

**Comment by christiansievers** [comment]
turns out it's easy to control cec-client support to send HDMI hardware to sleep and wake it up again. But as it's outside the scope of this script here, I'll add it to my videolooper.de image, which seems to be the right place for it
