### ISSUE TITLE
On raspbian Bullseye omxplayer is no longer installable 

### ISSUE THREAD

**Issue by kaosbeat** [adafruit/pi_video_looper#151]
```
pi@raspberrypi:~/pi_video_looper $ sudo ./install.sh 
Installing dependencies...
==========================
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                                               
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                                       
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done             
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package omxplayer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'omxplayer' has no installation candidate
pi@raspberrypi:~/pi_video_looper 
```

And it seems like this will not be fixed https://forums.raspberrypi.com/viewtopic.php?t=324184

Is there an alternative player that can be installed? right now installation script fails on a fresh Bullseye Raspberry PI OS install. In the longterm  other fix than downgrade to buster will be needed...

**Comment by christiansievers** [comment]
Yes, that's true. As it says in the readme: Currently only the Legacy version of Raspberry Pi OS Lite is supported. You can download it from here: https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-legacy

Some people are working on porting the looper to cvlc. https://github.com/adafruit/pi_video_looper/tree/pb-bullseye
