### ISSUE TITLE
Fill or Stretch per video

### ISSUE THREAD

**Issue by mortotem** [adafruit/pi_video_looper#157]
Is there a way to make each video have its own fill or stretch? 
for instance most of my videos are 4:3 and fit my screen easier using the 'fill' function.
but some are 10:9, and the fill function is causing the top/bottom to be cut off. so the letterbox or stretch function might look better for these.

**Comment by tofuSCHNITZEL** [comment]
No, there is currently no way to do this. So I recommend you use an video editing software to place them and render them out at the same resolution.

**Comment by mortotem** [comment]
thank you for this.
