### ISSUE TITLE
Display Day of week, day of month, month and year on line 1, then hours : minutes : seconds on line 2 between videos feature request 

### ISSUE THREAD

**Issue by DanBaigo** [adafruit/pi_video_looper#161]
Hi all,

In v1.0.12 the time was implemented to appear between videos which is a fantastic feature added in by tofuSCHNITZEL (#155).

Could somebody please add in the feature for a second line and on line 1 be the date and line 2 be the time?

I've tried to do this myself but I've given up. Spent weeks on it hop and a catch and quite frankley will never get it to work.

**Comment by DanBaigo** [comment]
I have now created a fork with the above changes successfully implemented.

**Comment by tofuSCHNITZEL** [comment]
Thanks for the pull request! I will have a look and test it and then merge it in a new release. 
Cheers
