### ISSUE TITLE
current release (1.0.12) doesn't work with config from previous versions

### ISSUE THREAD

**Issue by theleiko** [adafruit/pi_video_looper#162]
Hi,
I just deployed a new pi, but pi_video_looper won't startup.
My workflow is: flashing image, running a script that does some standard config, installs pi_video_looper and loads a customized config file. So i used a config file that was last changed on v1.0.11, but on .12 it won't work, probably because of missing settings for datetime_display.

Maybe you can include a fix that if a specific config value is not found in the file, it will fallback to a standard value.

Thanks in advance and: amazing product :)

**Comment by tofuSCHNITZEL** [comment]
Hi,

why dont you just adapt your customized config file to include the newly added or changed values? (you could easily compare the two files with e.g a program like WinMerge)
alternatively so you don't get "surprised" you could "pin the pi_video_looper" version that gets installed via your script by not git clone the master branch but instead a specific release... and before you change the release in your script you check if there are configfile changes to be included.

But I will also think about adding fallback values to the config parser in the future.

cheers
