### ISSUE TITLE
image_player .gif support

### ISSUE THREAD

**Issue by HoZy88** [adafruit/pi_video_looper#165]
Hi there, Wanting to use image_player to play animated .gif from a usb unfortunately all .gif are static and they display as static for the amount of time specified under duration. 
Is there a fix for this? 

Hoping to play/loop/skip animated .gif

Thanks

**Comment by tofuSCHNITZEL** [comment]
Pygame does not allow for animated gif to be played. you should convert the gif to regular video files and use the video looper for the videos.
cheers
