### ISSUE TITLE
Splash video/screen

### ISSUE THREAD

**Issue by kasperinline** [adafruit/pi_video_looper#169]
Thanks you for a magnificent peace of software - I finde it very usefull for children as well as disabled people.

Is it possible to add a splashscreen or a splashvideo, that shows the next step (insert USB/USB-mount/USB-Changed)

Regards from Denmark

**Comment by tofuSCHNITZEL** [comment]
Hi,
there is the function of "idle message" that displays "Insert USB drive with compatible movies." if no usb stick is found. you could modify this text in the python source.
there is no real way currently to display a video instead of the idle text.

cheers
