### ISSUE TITLE
HyperPixel 2.1 inch Round Display and Pi Video Looper Issue

### ISSUE THREAD

**Issue by dannpye** [adafruit/pi_video_looper#171]
Hey there, 
I am having an issue getting the HyperPixel 2.1 inch round display working with Video Looper. 

I have a Raspberry Pi 3 B, and the screen is just mounted to the GPIO. I see the desktop boot up fine when I switch it on, but then the screen goes blank when there would normally be the "please insert a USB" splash screen. 

When I disable running Video Looper I suddenly can see the splash screen as it is disabling, then it freezes. When I reboot and enable it again, it goes blank again.

I have tried changing the video_looper.ini line
extra_args = --no-osd --audio_fifo 0.01 --video_fifo 0.01 --align center --font-size 55

To include 
extra_args = --no-osd --audio_fifo 0.01 --video_fifo 0.01 --align center --font-size 55 --display 4

Which would be the same number assigned for a GPIO touch screen as I understand for omxplayer. 

I have seen that there is a person who has managed to get it working. If anyone has any insight, that would be amazing. Cheers.

**Comment by tofuSCHNITZEL** [comment]
have you tried? https://github.com/adafruit/pi_video_looper/issues/142#issuecomment-1400043806
