### ISSUE TITLE
Hardware Requirements?

### ISSUE THREAD

**Issue by JayHoltslander** [adafruit/pi_video_looper#175]
I searched the docs but couldn't find an answer on this. What are the minimum hardware requirements to run pi_video_looper?
(Need to build myself a shopping list.)

_Disclaimer: I'm currently a total newb with Raspberry Pi._

**Comment by tofuSCHNITZEL** [comment]
The video_looper should run on all Raspberry Pis - also the older ones but I would recommend RPi 3B+ (if you can find any currently)
