### ISSUE TITLE
Where is 1.1.0 ?

### ISSUE THREAD

**Issue by GLOUPY-RnD** [adafruit/pi_video_looper#176]
Hi,
in the changelog there is a new 1.1.0 version using CVLC but I don't find it anywhere ?
[It is written on this page](https://github.com/adafruit/pi_video_looper/tree/pb-bullseye#readme)
Thanks.

**Comment by JonnyTech** [comment]
From the readme, follow the install instructions:

```
sudo apt-get install git
git clone https://github.com/adafruit/pi_video_looper
cd pi_video_looper
sudo ./install.sh
```

**Comment by tofuSCHNITZEL** [comment]
It's not released yet and also not really functional. use at your own risk or help finish the development. Thanks! 

Cheers
