### ISSUE TITLE
Can't log into the system after quiet exit (esc)

### ISSUE THREAD

**Issue by Gacmat** [adafruit/pi_video_looper#178]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.): DietPi/Buster

- Python version (run `python -version` or `python3 -version`):  none

- Error message you are receiving, including any Python exception traces:  `Login incorrect`

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 
1. Download image from [HERE](https://videolooper.de/video_looper_v2.6.zip) (its videolooper.de)
2. Install it on the SD card by Raspberry Pi Imager and set it to create my own account on it 
3. Put SD card into RPi4B (4GB) 
4. When VideoLooper start hit `ESC` button for quiet exit
5. Try to login with default `dietpi` password to `root`, `dietpi` or own account

I tried with configuring it also in files like `dietpi.txt` or `config.txt` - but it was not working also

I tried setting also `dietpi-wifi.txt` but it also didn't worked.

Is it something wrong with the image from videolooper.de?

What are default login credentials?

**Comment by christiansievers** [comment]
Hi, here you go:> Good to know before editing the systemThe operating system's password was changed to videoThis is from videolooper.de - if you have suggestions how to make it easier to read, more accessible, I’m all ears…All the bestAm 18.03.2023 um 20:36 schrieb Mateusz Gackowski ***@***.***>:﻿


Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.): DietPi/Buster


Python version (run python -version or python3 -version):  none


Error message you are receiving, including any Python exception traces:  Login incorrect


List the steps to reproduce the problem below (if possible attach code or commands
to run):



Download image from HERE (its videolooper.de)
Install it on the SD card by Raspberry Pi Imager and set it to create my own account on it
Put SD card into RPi4B (4GB)
When VideoLooper start hit ESC button for quiet exit
Try to login with default dietpi password to root, dietpi or own account

I tried with configuring it also in files like dietpi.txt or config.txt - but it was not working also
I tried setting also dietpi-wifi.txt but it also didn't worked.
Is it something wrong with the image from videolooper.de?
What are default login credentials?
