### ISSUE TITLE
change audio on mkv video

### ISSUE THREAD

**Issue by Crover81** [adafruit/pi_video_looper#188]
hi, i should have to change audio track of a mkv, it should be possible with omxplayer, but among the enabled keyboard commands there is no this option, it could be a useful option for other people too

Is it possible to do something?
Thanks

**Comment by Redacted99** [comment]
Which keys in omxplayer switch streams?  Is it j and k?

**Comment by Crover81** [comment]
Exactly,

 j = Previous Audio stream
k = Next Audio stream

**Comment by Redacted99** [comment]
I did something similar, I added a pause resume capability using the space key mapped to a omxplayer key command.   Adding j and k support would be similar.  Copy my code and change the bindings and action.  Branch 163 on my fork.  Redacted99/pi_video_looper.

Hope this helps
