### ISSUE TITLE
Disable loop

### ISSUE THREAD

**Issue by simonemarin** [adafruit/pi_video_looper#189]
Hallo this is a feature/help request, how would it be the easiest way to disable the looping function? I need it just to play once a single video.
Thanks

**Comment by JonnyTech** [comment]
Hahaha, forgive my response but I could not help it... This project is pi-video-LOOPER - there is a clue in the name - you need to use a video player, of which there are many. One would not say, how can I drive my car in the ocean, rather than use a boat...

**Comment by simonemarin** [comment]
Yes you may be right, but this project has all the right setup already (pygame for a nice blank startup, etc.) I have used it for many years and I still think that , despite the name, using it as a single shot video, together with the keyboard shortcuts, would be within   the user case, so to say.

**Comment by shell3000** [comment]
Makes sense in an exhibition context, with an external trigger to start a video, motion detection, light, button and so on. VideoLooper exist mostly in this environment, so this question is relevant.

**Comment by Oppfields** [comment]
This would be a good option to add, there are many occasions where a 'one shot' function could be useful in events, gallery and installation settings.

**Comment by tofuSCHNITZEL** [comment]
I plan to add this in the next version - you can find a work in progress solution in the current next branch https://github.com/adafruit/pi_video_looper/commit/4b0c616106ac19b24ed902309d3eabf5695f36d2

**Comment by tofuSCHNITZEL** [comment]
> Makes sense in an exhibition context, with an external trigger to start a video, motion detection, light, button and so on. VideoLooper exist mostly in this environment, so this question is relevant.

check out the new GPIO control feature added in version https://github.com/adafruit/pi_video_looper/releases/tag/v1.0.14

**Comment by tofuSCHNITZEL** [comment]
> Hallo this is a feature/help request, how would it be the easiest way to disable the looping function? I need it just to play once a single video. Thanks

done.
this is now possible in https://github.com/adafruit/pi_video_looper/releases/tag/v1.0.15
