### ISSUE TITLE
Is it possible to run 1 single video stretched on 2 displays?

### ISSUE THREAD

**Issue by ygreq** [adafruit/pi_video_looper#192]
Hi folks! 

I would like to play a video that stretched on 2 monitors. So the resolution for that specific video would be 7680 x 2160 pixels (meaning 2 times 4k). Or at least 3960 x 1080 (2 times 1080p)

Do you know if this is possible?
Thank you so much! 

LE: Ok. I found out 4k is out of the question. But can I do this with fullHD?

**Comment by tofuSCHNITZEL** [comment]
Hi,
I dont know if this is technically possible - if its possible to span a video over both hdmi outputs with the rpi4 then it will only work with cvlc which still does not work with video_looper...
sorry.
cheers
