### ISSUE TITLE
Specify omxplayer aspect ratio

### ISSUE THREAD

**Issue by ole-worm** [adafruit/pi_video_looper#194]
My 16:9 video is getting cut off in the display. I configured the PiOS display correctly, but omxplayer will extend past the display. With omxplayer I can set the aspect ratio using CLI options (ex. omxplayer --loop --blank --no-osd --aspect-mode letterbox --win 32,0,675,480 /file.mp4). Where can I add this in the omxplayer.py and/or video_looper.py script?

**Comment by tofuSCHNITZEL** [comment]
Hi,
check /boot/video_looper.ini option "extra_args".
cheers
