### ISSUE TITLE
Running a video based on specific time

### ISSUE THREAD

**Issue by 0xAazaad** [adafruit/pi_video_looper#195]
I have 2 videos 'a' and 'b'.

I want video a to loop continuously. 
video b to run every even hour (0000 hrs, 0200, hrs, 0400 hrs...) once and then go back to looping a. 

I also want to be able to choose different volumes for both videos. 

Can someone help with achieving this?

Thanks in advance.

**Comment by shell3000** [comment]
You can use a script to move your files in and out of you video folder, here /home/pi/video:

#/bin/bash

mv /home/pi/video/b.mp4 /home/pi/video_off
mv /home/pi/video_off/a.mp4 /home/pi/video

# videoduration a.mp4
sleep 30

mv /home/pi/video/a.mp4 /home/pi/video_off
mv /home/pi/video_off/b.mp4 /home/pi/video

Afterwards you modify your crontab to start the script at your given time:

0 0 * * * /bin/bash /home/pi/timer.sh >> /home/pi/timer.log 2>&1
0 2 * * * /bin/bash /home/pi/timer.sh >> /home/pi/timer.log 2>&1
0 4 * * * /bin/bash /home/pi/timer.sh >> /home/pi/timer.log 2>&1
0 6 * * * /bin/bash /home/pi/timer.sh >> /home/pi/timer.log 2>&1

It works very well.

**Comment by 0xAazaad** [comment]
Thank you. 
What's a good way to autorun this on start?

**Comment by shell3000** [comment]
crontab -e

**Comment by tofuSCHNITZEL** [comment]
@shell3000 good solution! this is probably the best solution for this besides creating a whole scheduler function/code in video_looper
