### ISSUE TITLE
lightening bolt upper right

### ISSUE THREAD

**Issue by briandmiller** [adafruit/pi_video_looper#200]
Is there a way to hide the lightening bolt in the upper right hand corner of the screen?

Everything else about this videolooper is fantastic.

Thanks

**Comment by briandmiller** [comment]
Never mind. I just learned it is a notification that my power supply is less than adequate.

**Comment by tofuSCHNITZEL** [comment]
and you can hide this warning by adding "avoid_warnings=1" to /boot/config.txt

`sudo sh -c "echo 'avoid_warnings=1' >> /boot/config.txt"`
