### ISSUE TITLE
OMX player not found in installation

### ISSUE THREAD

**Issue by evanthemann** [adafruit/pi_video_looper#205]
When trying to install, I get this error. 

Package omxplayer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'omxplayer' has no installation candidate

I'm installing on Pi OS Lite (legacy) as suggested.

**Comment by tofuSCHNITZEL** [comment]
Hi.

The last working image is this one: https://downloads.raspberrypi.com/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2022-01-28/2022-01-28-raspios-buster-armhf-lite.zip
