### ISSUE TITLE
GPIO input for player and device command

### ISSUE THREAD

**Issue by anoril1979** [adafruit/pi_video_looper#209]
It is possible to control the RaspPi with keyboard, like 'p' to shutdown, and have GPIO interrupts to change video played.

Is it possible to add RaspPi commands (shutdown) to GPIO interrupts ?

Regards,

**Comment by tofuSCHNITZEL** [comment]
yes did you even read the readme?
https://github.com/adafruit/pi_video_looper#control

you can edit the code to make the gpio also run the shutdown action.

**Comment by anoril1979** [comment]
Hi!
Great!

Sorry, I'm new to RaspberryPi programming, and yes: I read the readme which I found not really clear on this point (it literally says you have actions on keys, and GPIO Can be mapped to filenames, file indexes or relative jumps :) )

Many thanks for your time replying my request and for this great piece of work!

And I wish you the best for the New Year!
Regards
