### ISSUE TITLE
no files found in home/pi - when using hello_video

### ISSUE THREAD

**Issue by mikolaskova** [adafruit/pi_video_looper#21]
Hello,

 when I try to use video-looper with the hello_video option, it says no files found in home/pi,  although there is a .h264 video file (I normally can play this with hello_video- its te test.h254 from the hello_video folder...*)- what can I do to make video_looper play this file with hello_video?

I already tried to remove the volume parameter as proposed in https://github.com/adafruit/pi_video_looper/issues/6 but that did not help.

Best regards

Adriana

*when doing hello_video.bin ./myfile.h264 directly

**Comment by tofuSCHNITZEL** [comment]
currently there should be no issues.
if the file has the correct ending for the mode the player is in. it should be picked up by the looper.
If you still have trouble feel free to open another issue.
