### ISSUE TITLE
Block Button Press while playing a video

### ISSUE THREAD

**Issue by fiete96** [adafruit/pi_video_looper#226]
Hey there,
Thanks for this nice Application! but for me there is one thing missing:
I would like to an option to deactivate the GPIO Button while the video is playing. so the video doesn't jump to the start of the clip if its already playing and someone presses the button again.
I want to use this with the single shot option to play the video once.
Thanks a lot!

**Comment by tofuSCHNITZEL** [comment]
Hi,
okay such an option would only make sense if the player "stops" after a video - otherwise the buttons would never work ;)
I will see if this is easy to do!
cheers

**Comment by fiete96** [comment]
Hey!

Thanks! I tried it, but unfortunately, it didn't work. I addressed the video directly in the GPIO Map, but then the function does not work. When I address K_s, it works partially. I cannot play the video from the start while the video is running. However, I think it stored that I pressed it while it was playing, and then it played the video two times.

I hope you understand what I mean. :D

**Comment by tofuSCHNITZEL** [comment]
sorry I had some stupid oversights in the code I pushed first... all fixed now and I tested it and now it works as expected. please test again ;)

**Comment by tofuSCHNITZEL** [comment]
Great! Its now in the 1.0.19 release version.
https://github.com/adafruit/pi_video_looper/releases/tag/v1.0.19
