### ISSUE TITLE
Copy Files

### ISSUE THREAD

**Issue by philspitlerSF** [adafruit/pi_video_looper#228]
Hi, I am using Videolooper 2.8 and it works great reading my files from the USB drive.

When I enable copy mode, it starts to copy the file but once it get's to about 50% of the copy, it reboots and gets stuck in a cycle.

The mp4 file is 765mb.

**Comment by tofuSCHNITZEL** [comment]
Hi,
sounds to me like a corrupt file / sd card / usb stick. 
have you tried with a different file / sd card (fresh flash) / usb stick?

**Comment by christiansievers** [comment]
Yup. Or there isn’t enough space on the SD card. Have you expanded it? As usual with raspi-config.

**Comment by tofuSCHNITZEL** [comment]
> Yup. Or there isn’t enough space on the SD card. Have you expanded it? As usual with raspi-config.

ah yes of course - @philspitlerSF what is the output of "lsblk" and "df -h"

**Comment by philspitlerSF** [comment]
The file / USB are not corrupt but it could be a file size  issue. I thought I read that the file system was already expanded in the image file I burned.

I'll test it using the comments suggested here and report back.

**Comment by philspitlerSF** [comment]
It was a file size issue, I misread the documentation and thought it said the file system had already been expanded. It works great now. Thanks

**Comment by tofuSCHNITZEL** [comment]
Nice!
