### ISSUE TITLE
Unable to mount the usb key RW

### ISSUE THREAD

**Issue by thecrazy** [adafruit/pi_video_looper#3]
I modified the folloing line in /boot/video_looper.ini from:

readonly = true

to:

readonly = false

But the key is still set readonly.

**Comment by thecrazy** [comment]
Mmm... will have to double check I think it may have been a permission issue.

**Comment by tdicola** [comment]
Ah thanks for checking, yeah I don't see anything in the code that should cause an issue like you saw.  I'll close this for now but feel free to re-open if you run into it again.
