### ISSUE TITLE
Loop Once

### ISSUE THREAD

**Issue by edwardtamkingfai** [adafruit/pi_video_looper#30]
Hi, 

Thanks for your great work. Is there option to play the list only once? If not, I would suggest adding this feature.

**Comment by Gary202** [comment]
i 2nd also would be nice play file x number of times but randomly

**Comment by tofuSCHNITZEL** [comment]
> i 2nd also would be nice play file x number of times but randomly

this should be possible now by adding _repeat_Nx to the filename (where N is a positive integer)
