### ISSUE TITLE
Change messages into another language

### ISSUE THREAD

**Issue by pittipuk** [adafruit/pi_video_looper#32]
Hi,
how (where !) can I change the messages like "Insert USB drive with compatible movie..." ?
I want to use the videolooper in another language.
I didn´t find the file, where I have to change the messages.
Thanks for your help!

**Comment by reggae-shark** [comment]
Same question! I'd like to have no text

**Comment by arturodr** [comment]
before installing change the file: 
```
Adafruit_Video_Looper/usb_drive.py
```
around line line 40 you'll see:

```python
def idle_message(self):
        """Return a message to display when idle and no files are found."""
        return 'Insert USB drive with compatible movies.'
```
Just change that function to return  your desired message.

**Comment by whiteaden** [comment]
@arturodr this is great, the predicament I'm running into is breaking the instructions into multiple lines; `\n` doesn't seem to work, it just shows a ⍰ on my display instead of dropping stuff on another line.

I'm a scrub with python so maybe it's not a possibility in the way the idle_message is set up.

**Comment by arturodr** [comment]
@whiteaden AFAIK idle_message is only used by a print() function at video_looper.py 

I have no way to test it right now but something lie this should work:
```python
def idle_message(self):
        """Return a message to display when idle and no files are found."""
        return """First Line
Second Line
...
Last Line"""
```

**Comment by tofuSCHNITZEL** [comment]
I will close this for now. If anyone knows how to properly create translations for pythons scripts (maybe gettext?) feel free to create a pull request.
