### ISSUE TITLE
omxplayer keys not working

### ISSUE THREAD

**Issue by MelGrubb** [adafruit/pi_video_looper#38]
I've seen this reported a couple times on the AdaFruit forums, but no-one seems to have a solution. I'm opening this issue simply as a means of tracking the issue. OmxPlayer on its own responds to keyboard commands (play/pause/rew/etc.) just fine, but not when being run through the looper script. It seems that keys have no effect when looping. For the most part, the looper is meant to run unattended, but there are times when something goes wrong, the power goes out, or something else happens that's outside of your control, and restarting the playlist from the beginning is not always appropriate. The ability to fast forward and "catch up" with where the video should be is sometimes very important.

Whatever is wrong seems to be in the interaction between the looper script and omxplayer.

**Comment by tofuSCHNITZEL** [comment]
with v1.0.4 basic start stop and skip functionality is implemented.
maybe in the future if I (or someone) reworks the way omxplayer is called this issue can be solved
