### ISSUE TITLE
Open terminal window issue

### ISSUE THREAD

**Issue by koaling** [adafruit/pi_video_looper#41]
Good afternoon,

I would like to know how can I open a terminal window when videos are playing. Is there any key combination?

Thanks in advance

**Comment by m-p-3** [comment]
Your best option is to remotely connect to it over SSH.

**Comment by brennen** [comment]
For the moment, m-p-3 is probably correct. I just merged #25, which allows hitting Esc to exit, so that might also meet your needs.
