### ISSUE TITLE
How to add 1 Button to zap videos?

### ISSUE THREAD

**Issue by alexlechot** [adafruit/pi_video_looper#46]
I would like to add a button that when pressed, go to the next video.

What would be the document to edit?

**Comment by alangstein** [comment]
I would also like this functionality!

**Comment by tofuSCHNITZEL** [comment]
I've already coded it, just have to test it and release ;)

**Comment by tofuSCHNITZEL** [comment]
it is done ;)
implemented with v1.0.4
press k for sKip
and press s for start/stop
