### ISSUE TITLE
Issue plugging usb

### ISSUE THREAD

**Issue by Waldous** [adafruit/pi_video_looper#47]
Good afternoon all,

I am quite begginer on this, I have installed video looper without a problem. The problem comes when I plug the pen drive and does not play the content. I have realised when I plug it, RPI recognised the pendrive but does not read it?

When I stop the application, there is an Authentication windows to authenticate the USB DISK. Is there any where to disable this option?

Looking forward to hear from you guys.

Many thanks in advance :)

P.S I've Raspberry Pi 3 (Model B).

**Comment by ademeglio** [comment]
@Waldous , I ran into a similar issue the other day but it was the format of the drive that seemed to cause the issue. Check to see what the file system format is. If it is exFat. If it is format as Fat32.
