### ISSUE TITLE
Raspi 3 B+ mountpoint fix

### ISSUE THREAD

**Issue by ladyada** [adafruit/pi_video_looper#48]
https://forums.adafruit.com/viewtopic.php?f=8&t=138174

**Comment by brennen** [comment]
We can remove automounting from the file manager config by changing a couple of values in `~/.config/pcmanfm/LXDE-pi/pcmanf.conf` with sed or whatever.  I haven't been able to reproduce an issue where USB volumes are mounted in the wrong place and cause actual breakage, but I can easily enough believe that might happen in some cases.

I'm not sure whether this has much to do with the desktop flashing into view briefly before player fires up.  Trying to figure that out.

**Comment by tofuSCHNITZEL** [comment]
please check if the issue still persists with the newest versions of pi_video_looper. I could not replicate any mounting issues.
