### ISSUE TITLE
Delay between the movies?

### ISSUE THREAD

**Issue by SemdeRoos** [adafruit/pi_video_looper#49]
Is it possible to put a delay between the movies?

**Comment by tofuSCHNITZEL** [comment]
check out v.1.2.2 of my pi_video_looper fork for this functionality
https://github.com/adafruit/pi_video_looper/

**Comment by SemdeRoos** [comment]
Nice thanks!!

Kind regards,
Sem de Roos

Met vriendelijke groet,
Sem de Roos


Verstuurd vanaf mijn iPhone

Op 16 mrt. 2019 om 00:49 heeft Tobias Perschon <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


check out v.1.2.2 of my pi_video_looper fork for this functionality
https://github.com/adafruit/pi_video_looper/

**Comment by tofuSCHNITZEL** [comment]
@SemdeRoos is feature is also implented in this repository with version 1.0.2
