### ISSUE TITLE
Feature Request:  Do not automatically start program after installation

### ISSUE THREAD

**Issue by nsummy** [adafruit/pi_video_looper#56]
this program essentially bricks your raspbian installation if you don't have ssh server enabled OR if you do but don't have access to a LAN.  Following the running the install script the program just starts automatically.  There is no way to stop it locally because keyboard control is disabled by default.

2 extremely simple solutions:  Either don't automatically start the program after installation or at least enable keyboard control by default.  If neither of these solutions are acceptable I think at the bare minimum a warning should be in the instructions letting the user know the only way to stop this program is via an ssh command

**Comment by tofuSCHNITZEL** [comment]
Fair point. I actually never thought about setting up a rpi not via ssh ;)
I pushed an update with keyboard control enabled by default.
but maybe not auto starting and just telling the user after the install that it will run on next reboot might be better- not sure yet ;)
