### ISSUE TITLE
Files on Sd card

### ISSUE THREAD

**Issue by Gary202** [adafruit/pi_video_looper#60]
I have this set up on a pi zero with a network share on the SD card once files are uploaded the video play doesn't see the files until the pi reboots. any help would be awesome. 
Class photos via a network share that my class mates can add to!

**Comment by tofuSCHNITZEL** [comment]
Hi!
you could use supervisorctl restart video_looper over ssh, but you probably would want the player to automatically reload. 
I will have a look if this can be implemented easily!

**Comment by tofuSCHNITZEL** [comment]
hey! check out (just released) version 1.0.2.
The directory mode now recognises changes in the number of files in the directory and reloads the playlist.
beware: the file will start playing even if its still copying (e.g. a slow network connection) I've tested this but it seems there were no real issues with it

**Comment by Gary202** [comment]
one thing when the folder where it pulls the files from is empty and files are added nothing happens till a restart. Whats the command to restart supervisorctl ? I can just do a cron to restart the program everyday?

**Comment by tofuSCHNITZEL** [comment]
Are you sure? I will check and fix it if this is the case. You can use the newly added reload.sh to restart the looper or check the bottom of the file for the command you could use directly in a cron.

**Comment by Gary202** [comment]
yea I tested it just now but it does update the playlist if a new file is added. I'll just call reload.sh in a Cron job just to make sure it's playing. Thank you for your help. Is there a way to remove the black screen in-between each video?

**Comment by tofuSCHNITZEL** [comment]
The pause between each video mostly depends on the speed of your raspberry setup, how fast it can load the files one after another. (if the new delay between video options is 0) 
there is also the possibility to use an image instead of the black background or you could change the background color.

**Comment by tofuSCHNITZEL** [comment]
> one thing when the folder where it pulls the files from is empty and files are added nothing happens till a restart.

I just tested it myself with a fresh install and this is not the case. Folder is empty - it displays the no files message; you drop in files (e.g. via smb) it starts playing - I delete everything in the folder it goes back to the no files message

**Comment by tofuSCHNITZEL** [comment]
> is it possible to scroll through different pictures in between each video. 
no this is not possible at the moment,

**Comment by tofuSCHNITZEL** [comment]
> 
> 
> at the moment but is possible down the road?

I have to think about how to do it - it will probably go together with a playlist feature
