### ISSUE TITLE
Random play order

### ISSUE THREAD

**Issue by lilmansplace** [adafruit/pi_video_looper#66]
I'm in love with your project here and thank you so much.
I do wish there was a random ordering to the videos played.
I used this for digital decoration effects for halloween and having the files play in the same order as they are on the usb storage makes it lose some of it's affect.  Would love to be able to randomize the play order.
Like making an array of filenames that are possible to play and using the python random.choice() function.

**Comment by tofuSCHNITZEL** [comment]
You can do this already with the is_random setting in the ini.
