### ISSUE TITLE
Random video issue

### ISSUE THREAD

**Issue by Gary202** [adafruit/pi_video_looper#68]
I'm having a issue where the video randomly will freeze up or it won't fully play the entire file??

My gpu split is 128

**Comment by tofuSCHNITZEL** [comment]
Does your pi have sufficient power?
have you tried reinstalling it on a fresh SD card?

**Comment by Gary202** [comment]
Yea I'm useing a pi zero with a 2amp power brick.
Also I made a master image and copyed the SD card to several pis and 2 out of the 5 are having issues. And if I change the pi it still has the issue

**Comment by tofuSCHNITZEL** [comment]
Sounds like maybe a faulty SD card?

**Comment by Gary202** [comment]
How can determine if it's exactly the SD card?

**Comment by christiansievers** [comment]
You usually get strange output while booting up. Can be shown again later with 'sudo dmesg'.

**Comment by Gary202** [comment]
Great thank you

**Comment by Gary202** [comment]
Ok I'll have to test another card and see the results

**Comment by Gary202** [comment]
what should i be looking for when i run "sudo dmesg" i have several line in red???

**Comment by Gary202** [comment]
The video keep freezeing not sure where to go.
i have tried 2 different SD cards. 
one card the video freezes with in the 1st 30 min.
the other card it freezes like 5 hours in.
any help would be appreciated

**Comment by Gary202** [comment]
also have increased the video ram to 192

**Comment by Gary202** [comment]
[dsmesg.txt](https://github.com/adafruit/pi_video_looper/files/3746018/dsmesg.txt)

**Comment by tofuSCHNITZEL** [comment]
@Gary202 did you solve it?

**Comment by Gary202** [comment]
not sure if it was the pi itself or the SD card
