### ISSUE TITLE
Text scrolling

### ISSUE THREAD

**Issue by Gary202** [adafruit/pi_video_looper#69]
Is it possible to add text scrolling to the bottom of the display?? While the video is playing???

**Comment by tofuSCHNITZEL** [comment]
I think adding aditional videodata while omxplayer is playing is not that easy... so maybe static title would be sufficient for you? https://github.com/adafruit/pi_video_looper/pull/67

**Comment by Gary202** [comment]
Static??

**Comment by tofuSCHNITZEL** [comment]
Not scrolling - just text, like subtitles

**Comment by Gary202** [comment]
ooo if that possible! it could read it from a text file on the pi

**Comment by Gary202** [comment]
what about something like this

https://www.raspberrypi.org/forums/viewtopic.php?t=102499
