### ISSUE TITLE
Shutting Down

### ISSUE THREAD

**Issue by elalemanyo** [adafruit/pi_video_looper#8]
Hi,
I want to use the pi_video_looper for a project, but I am not sure how will be the best way to shut down, because on the installation I just have the pi connected directly to a TV with the HDMI. And I read that if  I yank out the power cord as will corrupt the Pi's SD card and require a full operating system and video looper reinstallation.

Thanks!

**Comment by tdicola** [comment]
Great question!  If you're shutting down infrequently and the Pi is on your network, check out the Pi finder tool and use its shutdown button to cleanly shutdown the Pi before powering it down: https://learn.adafruit.com/the-adafruit-raspberry-pi-finder/overview  

If the Pi isn't on a network and you only have physical access to it, you probably want to make a little shutdown button that kicks off a script to cleanly shutdown the Pi.  There are lots of write-ups out there on it, but this looks like a fairly complete one to check out: http://www.instructables.com/id/Simple-Raspberry-Pi-Shutdown-Button/?ALLSTEPS
