### ISSUE TITLE
Home folder on pi

### ISSUE THREAD

**Issue by Gary202** [adafruit/pi_video_looper#81]
I have pi user name changed for security resons. I see when installing the pi_video_player it creates "/home/pi/video" were could i cange the install script to use the currect home folder "$HOME/video"  when installing??

**Comment by Gary202** [comment]
or on the next version could the changed be included??

**Comment by tofuSCHNITZEL** [comment]
Sure good point. I will try to do it today.

**Comment by tofuSCHNITZEL** [comment]
the creation of the folder in /home/pi/video with the installer is just for convenience. just create a folder yourself (wherever you want) and enter the path in /boot/video_looper.ini

**Comment by Gary202** [comment]
Correct but since I'm not useing the pi user and the home folder is a different name. Once the installation is completed I have to remove the pi/ folder the installation creates. If your installation uses $HOME it will create a folder in the current home directory
