### ISSUE TITLE
Video freezing 

### ISSUE THREAD

**Issue by Gary202** [adafruit/pi_video_looper#83]
What would cause video freezing?? The os is not frozen? just the video
My set up
Board = Pi zero w
OS = Rasbian stretch lite
Player = Hello video
ram split = 128
sd card = Sandisk 16 gig Class-10 UHS-1 A1

**Comment by tofuSCHNITZEL** [comment]
Please post your video_looper.ini

**Comment by Gary202** [comment]
Sorry for the let reponse was on vacation
The video freezes randomly  here is the video_looper.ini
[video_looper.ini.txt](https://github.com/adafruit/pi_video_looper/files/3944239/video_looper.ini.txt)
and i have around 12 or 13 .h264 files

**Comment by tofuSCHNITZEL** [comment]
please try to disable keyboard_control.
also maybe try with a differnet SD card or maybe the files are somehow corrupted and hello cannot handle them...
is there a reason why you would use hello video? why not use regular mp4 h264 files and use omxplayer?

**Comment by Gary202** [comment]
I need the seemless playback of several files back to back omxplays has a pause in between each file.

**Comment by tofuSCHNITZEL** [comment]
as far is I know there will be a gap between different files even with hello_video

**Comment by Gary202** [comment]
The gap with omxplayer on the pi zero is around 3. seconds the gap with hello video is around .8 seconds

**Comment by tofuSCHNITZEL** [comment]
Have you tried to disable the keyboard control?
Have you tried switching the ad card?

**Comment by Gary202** [comment]
yes i have tryed and the video just hangs not sure what the issue is

**Comment by tofuSCHNITZEL** [comment]
Maybe the issue somehow is with the video file itself or with the rpi hardware.
Would it be possible for you to send me the video and I try it?

**Comment by Gary202** [comment]
so with the keyboard control disabled i see the cpu load drop 50%!! on the pi zero with keyboard controller enabled the cpu load is around 85% with it disabled the load is around 35% is this correct? with the keyboard control disables how do i quiet the video playback???

**Comment by tofuSCHNITZEL** [comment]
Over ssh would be the only possibility at the moment.

**Comment by Gary202** [comment]
video freezing has stoped not sure what the issue was??
I have disabled the keyboard controlls

**Comment by tofuSCHNITZEL** [comment]
> 
> 
> video freezing has stoped not sure what the issue was??
> I have disabled the keyboard controlls

if you have time maybe try it with the v1.0.7 - the cpu usage caused by the keyboard control handling was improved there
