### ISSUE TITLE
Stop script over VNC

### ISSUE THREAD

**Issue by adinhalilovic** [adafruit/pi_video_looper#84]
Hi,
i'm using raspberry pi 3 with raspberry desktop raspbian. I need to have control of my raspberry over VNC, since its far away from me. When i connect to raspberry with VNC i cant stop video(ESC dont work), actually cant do nothing since my screen is all black. Is it possible to help me fix this ? Can i fix something in source ?

**Comment by christiansievers** [comment]
Can’t you control it via ssh? That works like a charm.

**Comment by adinhalilovic** [comment]
I can't do port forwarding since i don't have access to router

**Comment by tofuSCHNITZEL** [comment]
but VNC works?
you could also try https://www.howtoforge.com/reverse-ssh-tunneling

**Comment by adinhalilovic** [comment]
Yea, VNC works fine, I can connect to my rasp, but i only got a black screen and cant do anything.

**Comment by christiansievers** [comment]
and port forwarding for VNC is set up on the router?

**Comment by adinhalilovic** [comment]
I installed vnc server on raps and just log in into my account. On other side(my laptop) i installed vnc viewer app and thats it. There is no need to change anything about ports and stuff.

**Comment by christiansievers** [comment]
- when using VNC, are you on the same wifi or LAN or accessing the Raspberry from the outside?
- if you're local (and not from remote), logging in via SSH will work easily. Enable it from the Raspi's preferences, or in the Terminal via "sudo raspi config" first. Find out the Raspi's IP and log in from your computer with "ssh pi@(ip-address-here)", i.e. "ssh pi@192.168.0.2"
- once logged in, "sudo supervisorctl stop video_looper" will stop it. Likewise, "sudo supervisorctl start video_looper" will start it. Use the same with "restart", to, well you get it. 

- if you're logging in via VNC from remote, then there's already some kind of port forwarding set up. Find out what is set up and use that to also set up port forwarding for ssh. Be careful with these things, as you're basically inviting the whole big bad Internet into your local network. Make as the absolute minimum sure to give the Raspi a good and strong password.

**Comment by tofuSCHNITZEL** [comment]
Stale
