### ISSUE TITLE
Enable CopyMode

### ISSUE THREAD

**Issue by euripide2913** [adafruit/pi_video_looper#86]
Hi there, sound really silly but could you please guide me through on how to enable the CopyMode Function? I've been trying to enable this function to copy the video file on the pi but it's not working :(

**Comment by tofuSCHNITZEL** [comment]
first you have to enable the copymode via the ini.
set `file_reader = usb_drive_copymode` in /boot/videolooper.ini

take note, or better change the password in the "copymode" section of the ini file.

then you fill a usb drive with the videofiles you want on the player and then you create a file that has the same filename as the password set earlier (a file without file extension)

if you plugin this drive to the player you should see the copy progress window

**Comment by euripide2913** [comment]
Hi Tobias,
Thank you buddy for replying, I have a better idea now on how to do it!
Really appreciate your help on this
Cheers,
jp



On 13 Jan 2020, at 8:53 pm, Tobias Perschon <notifications@github.com<mailto:notifications@github.com>> wrote:


first you have to enable the copymode via the ini.
set file_reader = usb_drive_copymode in /boot/videolooper.ini

take note, or better change the password in the "copymode" section of the ini file.

then you fill a usb drive with the videofiles you want on the player and then you create a file that has the same filename as the password set earlier (a file without file extension)

if you plugin this drive to the player you should see the copy progress window
