### ISSUE TITLE
No files found with directory mode

### ISSUE THREAD

**Issue by thoperrot** [adafruit/pi_video_looper#91]
Hello !
I have some issues when I try to play a video from the micro SD card of my RPI 3B...
I didn't change the path of the configuration file so I put my videos in /home/pi/video in the partition rootfs.
However, my videos are not detected by the looper and they disappear from the folder "video" when I remove my SD card from the PC.
Anyone know about this problem ?

**Comment by tofuSCHNITZEL** [comment]
What OS are you using to put files on the SD? how did you "flash" the raspian to the SD?

**Comment by thoperrot** [comment]
Hello, I use the last version of Windows 10 with Win32DiskImager. I didn't
try to use Balena Etcher yet.

Le dim. 19 avr. 2020 à 10:25, Tobias Perschon <notifications@github.com> a
écrit :
