### ISSUE TITLE
Scaling to smaller screens.

### ISSUE THREAD

**Issue by Lt-Lemming** [adafruit/pi_video_looper#93]
I'm using Pi Video Looper with Pi Zero's running some 5" screens for a project.

These screens are only 800 x 480 resolution and are configured as such in the Pi's config.txt

One of the issues I have run into with it is that the error messages and the like don't scale to the smaller screen resolution. So I quite often end up with text that is off the screen and unreadable.

**Comment by tofuSCHNITZEL** [comment]
Hi,
thanks for the feedback. could you try the version in testing for me?
https://github.com/adafruit/pi_video_looper/tree/testing

`git clone --single-branch --branch testing https://github.com/adafruit/pi_video_looper/`

it should scale down the text for low-res screens - but I'm not sure if its enough.

Thanks!

**Comment by sirib123** [comment]
Hi! Was there any update on this? I've got a similar issue (using a 480x480 round hyperpixel screen). I've got letter boxing top and bottom only, and when I input a video file that is 480x480, it keeps the black letterbox on the top and bottom, but also stretched the video horizontally. I'd be incredibly grateful for help with this, as I'm needing it to work full screen for a deadline!

**Comment by tofuSCHNITZEL** [comment]
the above changes only affect the text size - it changes nothing with the output resolution...
do you have the bars also on bootup? do you have bars if you use a rpi with an os that has a desktop? how is the screen connected? if its HDMI you can try to change the overscan option for the rpi? (https://raspberrypi.stackexchange.com/questions/23094/calibrate-overscan-settings)

**Comment by sirib123** [comment]
Hi! Thanks for getting back so quickly! I've connected the Screen via the GPIO pins so it sits like a HAT on the pi. Booting up and the Raspberry pi desktop all look fine, no stretch, and no black borders. It's only once I launch videolooper that the text is cut off at each side ('insert USB') almost like it was forced into portrait mode. Then when I insert the file it stretches it, and the black bars remain on the left and right.

**Comment by tofuSCHNITZEL** [comment]
hm maybe its an issue with how omxplayer outputs the raw video data to the system.. unfortunately I have no experience with non hdmi screens on the pi... maybe you should also try a raspi os lite without desktop

**Comment by sirib123** [comment]
Yes I think it must be omx-player related, although I did try using the hello-video option too, and had the same issues! Are there any keywords you'd suggest searching?

**Comment by tofuSCHNITZEL** [comment]
Could you give me some more infos:
What make/model is the screen you are using?
Could you maybe provide a picture of how it looks:
On desktop
With the text displaying
With a video in 480x480 resolution paying
With a video in 1920x1080 resolution playing

**Comment by sirib123** [comment]
Hi! the screen is the 2.1 round screen from Hyperpixel (https://shop.pimoroni.com/products/hyperpixel-round)
I can take another picture of the desktop tomorrow, but it's centred and fills the screen, I can even see part of the tool bar at the top. Here's a test file I played via USB on the video looper;
Here's the original 16:9 file
<img width="1048" alt="Screenshot 2021-12-02 at 17 06 44" src="https://user-images.githubusercontent.com/95325457/144516657-9f6c1378-43f0-4d3c-bab8-0f61293e1e90.png">
Here it is on the round screen (squeezed and letterboxed)
![IMG_6401](https://user-images.githubusercontent.com/95325457/144516880-c5a51e45-3e2a-4a62-b68f-34df11226b3b.jpeg)
Here's the same file, but cropped to 480x480px
<img width="1041" alt="Screenshot 2021-12-02 at 17 06 33" src="https://user-images.githubusercontent.com/95325457/144516949-d0470c15-91b6-4497-adf8-ba1dbc365d5a.png">
and here is 480x480 on round screen, also squeezed and letterboxed, but this time letterboxed on left and right, not top and bottom like the 16:9 one (sorry for low quality!):
![Photo on 02-12-2021 at 17 18](https://user-images.githubusercontent.com/95325457/144517066-0e48f4ec-d4c0-4959-b6e5-d62cec6bd905.jpg)
This is the same for a 1080x1080 file:
![Photo on 02-12-2021 at 17 21](https://user-images.githubusercontent.com/95325457/144517273-7773e6a3-90bb-40e1-b797-b08afde9f879.jpg)
Very very grateful for any help with this and thanks for taking the time!!!

**Comment by kiswida** [comment]
hello, first of all sorry about my bad english. I have a Raspberry Pi Zero v.1.3, 1 GHz, 512 MB RAM and a 5 "display with hdmi and 800 * 480 resolution. Unfortunately, they don't work together. the pi zero whit a 27" fullhd monitor works fine, and the display whit my pc hdmi out is even fine together just gray strips... i took some pictures.
please help
than
![IMG_20211205_120515](https://user-images.githubusercontent.com/62474424/144746972-8a95df7d-d0d2-4e49-ab51-496e0e896286.jpg)
![IMG_20211205_120440](https://user-images.githubusercontent.com/62474424/144746973-fa523884-dc0e-431c-ac63-e5ce1f04e8bd.jpg)
![IMG_20211205_120409](https://user-images.githubusercontent.com/62474424/144746974-aceead1f-ba4e-4c03-b6e2-1971c55efc6d.jpg)
ks

**Comment by tofuSCHNITZEL** [comment]
@sirib123 
have you tried the different aspect mode options for omxplayer?

--aspect-mode

Letterbox, fill, stretch. Default: stretch if win is specified, letterbox otherwise

you can set this in the videolooper ini

**Comment by tofuSCHNITZEL** [comment]
> does the screen work if you install a full rasperrypi os with desktop? I'm not sure this kind of thing can be caused by the looper programm... (do you see the pi bootup text?)

**Comment by kiswida** [comment]
Hy, No it doesn't work, it just shows these gray sh*t all the time.

Thanks

**Comment by sirib123** [comment]
> @sirib123 have you tried the different aspect mode options for omxplayer?
> 
> --aspect-mode
> 
> Letterbox, fill, stretch. Default: stretch if win is specified, letterbox otherwise
> 
> you can set this in the videolooper ini

I believe I did try one of these (Fill?) and it came out with the same result. I don't have access to the screen at the moment, but will get back to you when I get access to it again and give it a go! (For now, as a temporary fix, I have stretched the video I was wanting to play in Premiere Pro in the opposite direction, and so it comes out un-stretched on the screen, albeit with a black border)

**Comment by kiswida** [comment]
hello,

i find the solution on youtube: https://www.youtube.com/watch?v=TYzOhgUmZcw&list=LL&index=3&t=42s

1.  create a ssh file
2. edit the config.txt: 
3. 
max_usb_current=1
hdmi_group=2
hdmi_mode=87
hdmi_cvt=800 480 60 6 0 0 0                # 800x480 on my display....
hdmi_ignore_edid=0xa5000080
config_hdmi_boost=2


Thanks !

**Comment by tofuSCHNITZEL** [comment]
great find!

**Comment by jayhoenes** [comment]
@sirib123 
I got the same problem with the hyperpixel screen and the pi_video_looper.
I think it's out of date now, but maybe it will help others with the same problem.

@tofuSCHNITZEL was right with the --aspect-mode, but it was hard for me to find the right place where to put the code. So here is the solution:

in /boot directory there is a video_looper.ini

Look for the line extra_args = .....  
here you add --aspect-mode fill
like this:

extra_args = --no-osd --audio_fifo 0.01 --video_fifo 0.01 --align center --font-size 55 --aspect-mode fill

**Comment by tofuSCHNITZEL** [comment]
thanks for pointing that out. sorry if I wasn't clear enough.
