### ISSUE TITLE
No fullscreen background image/color

### ISSUE THREAD

**Issue by pi43r** [adafruit/pi_video_looper#99]
I do not get a fullscreen background, when hitting the  `k` button to restart the video. There is a significant gap of ~100px on every side. My background image, video and monitor have all the same resolution of 1920x1080.

Is there any way to fix this or is it expected behavior?

Running version 1.0.7 on a RPi 3b & Zero W.

**Comment by tofuSCHNITZEL** [comment]
have you played around with the overscan settings?
https://raspberrypi.stackexchange.com/questions/23094/calibrate-overscan-settings

**Comment by pi43r** [comment]
Well, the video plays in full screen. Wouldn't the overscan setting chop things off at the edges?
I sent out the raspberries as is, so I can not test it anymore. Feel free to close this issue.
